###
POST http://localhost:80/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###
POST http://localhost:80/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNzMzMDUzMTcxLCJleHAiOjE3MzMwNTY3NzF9.3on-Sq-k6ZUf5QJugaOsPZprGJ2qJa80tKMsd0FPV7M
Content-Type: application/json


###
GET http://localhost:80/api/boards
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNzMzNjMzNjQ0LCJleHAiOjE3MzM2MzcyNDR9.E7mpR5a6prcoKl72zl2oZOJny7_D-klJqoRJ-VHrKD8

###
POST http://localhost:80/api/boards
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNzMzNjMzNjQ0LCJleHAiOjE3MzM2MzcyNDR9.E7mpR5a6prcoKl72zl2oZOJny7_D-klJqoRJ-VHrKD8

{
  "title" : "제목입니다.",
  "content" : "내용입니다.",
  "userId" : "1"
 }

###
GET http://localhost:80/api/boards/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNzMzNjMzNjQ0LCJleHAiOjE3MzM2MzcyNDR9.E7mpR5a6prcoKl72zl2oZOJny7_D-klJqoRJ-VHrKD8

###
PUT http://localhost:80/api/boards/1
Content-Type: application/json

{
  "title" : "제목입니다22.",
  "content" : "내용입니다22.",
  "userId" : "2"
}

###
DELETE http://localhost:80/api/boards/1
